const Quiz = require('../models/Quiz');
const { generateQuizFeedback } = require('./aiController');
const { validateYouTubeUrl } = require('../utils/youtubeValidator');
const { getTranscript } = require('../services/transcriptService');
const { generateQuizFromTranscript } = require('../services/aiService');

// @desc    Generate a new quiz from YouTube URL
// @route   POST /api/quiz/generate
// @access  Private (JWT Required)
const generateQuiz = async (req, res) => {
  try {
    const { videoUrl, content, numQuestions } = req.body;
    // Acceptable options for number of questions
    const ALLOWED_COUNTS = [5, 10, 15, 20];
    const requestedCount = Number(numQuestions) || 5;
    const questionCount = ALLOWED_COUNTS.includes(requestedCount) ? requestedCount : 5;

    const hasManualContent = typeof content === 'string' && content.trim().length > 0;
    if (hasManualContent) {
      const cleanContent = content.trim();
      if (cleanContent.split(/\s+/).length < 50) {
        return res.status(400).json({
          success: false,
          code: 'EMPTY_TRANSCRIPT',
          message: "We couldn't find enough content to generate a quiz. Please add at least a few paragraphs."
        });
      }

      const aiResult = await generateQuizFromTranscript(cleanContent, questionCount);
      if (!aiResult.success) {
        return res.status(502).json(aiResult);
      }

      const quiz = await Quiz.create({
        user: req.user._id,
        title: 'Quiz from study notes',
        summary: aiResult.data.summary,
        questions: aiResult.data.questions,
        totalQuestions: aiResult.data.questions.length,
        sourceType: 'manual'
      });

      return res.status(201).json({
        success: true,
        message: 'Quiz generated successfully',
        data: quiz
      });
    }

    // 1. Validate YouTube URL
    const urlValidation = validateYouTubeUrl(videoUrl);
    if (!urlValidation.isValid) {
      return res.status(400).json({
        success: false,
        code: 'INVALID_URL',
        message: urlValidation.message
      });
    }

    const videoId = urlValidation.videoId;

    // 2. Extract Transcript
    const transcriptResult = await getTranscript(videoId);
    if (!transcriptResult.success) {
      return res.status(400).json(transcriptResult);
    }

    // 3. Generate Summary & MCQs with Gemini AI
    const aiResult = await generateQuizFromTranscript(transcriptResult.transcript, questionCount);
    if (!aiResult.success) {
      return res.status(502).json(aiResult);
    }

    // 4. Save to MongoDB associated with current user
    const quiz = await Quiz.create({
      user: req.user._id,
      videoUrl,
      videoId,
      title: `Quiz: Video ${videoId}`,
      summary: aiResult.data.summary,
      questions: aiResult.data.questions,
      totalQuestions: aiResult.data.questions.length
    });

    res.status(201).json({
      success: true,
      message: 'Quiz generated successfully',
      data: quiz
    });
  } catch (error) {
    console.error('[QuizController] generateQuiz error:', error.message);
    res.status(500).json({
      success: false,
      code: 'SERVER_ERROR',
      message: 'Something went wrong while processing your request. Please try again later.'
    });
  }
};

// @desc    Calculate and save quiz attempt result
// @route   POST /api/quiz/result
// @access  Private (JWT Required)
const submitQuizResult = async (req, res) => {
  try {
    const { quizId, answers } = req.body;
    // answers format: [{ questionIndex: 0, selectedAnswer: "Option B" }, ...]

    if (!quizId || !Array.isArray(answers)) {
      return res.status(400).json({
        success: false,
        message: 'Please provide quizId and an array of answers'
      });
    }

    // Find quiz and ensure it belongs to the authenticated user
    const quiz = await Quiz.findOne({ _id: quizId, user: req.user._id });
    if (!quiz) {
      return res.status(404).json({
        success: false,
        message: 'Quiz not found'
      });
    }

    // Pure backend score calculation (Score is NOT generated by AI)
    let correctCount = 0;
    const evaluatedAnswers = [];

    quiz.questions.forEach((q, index) => {
      const userAnswerObj = answers.find((a) => a.questionIndex === index);
      const selected = userAnswerObj ? userAnswerObj.selectedAnswer : null;
      const isCorrect = selected === q.correctAnswer;

      if (isCorrect) {
        correctCount++;
      }

      evaluatedAnswers.push({
        questionIndex: index,
        selectedAnswer: selected,
        isCorrect
      });
    });

    const totalQuestions = quiz.questions.length;
    const incorrectCount = totalQuestions - correctCount;
    // Formula: percentage = (correctAnswers / totalQuestions) * 100
    const percentage = totalQuestions > 0 ? Math.round((correctCount / totalQuestions) * 100) : 0;
    // Pass when percentage >= 60
    const passed = percentage >= 60;

    // Save attempt to MongoDB
    quiz.isAttempted = true;
    quiz.score = correctCount;
    quiz.incorrectAnswers = incorrectCount;
    quiz.percentage = percentage;
    quiz.passed = passed;
    quiz.userAnswers = evaluatedAnswers;
    await quiz.save();

    let feedbackResult = {
      success: false,
      data: null,
      message: 'AI feedback is temporarily unavailable.'
    };

    try {
      feedbackResult = await generateQuizFeedback(
        quiz,
        evaluatedAnswers,
        {
          score: correctCount,
          totalQuestions,
          percentage,
          passed
        }
      );
    } catch (error) {
      console.warn('[QuizController] AI feedback generation failed:', error.message);
    }

    res.status(200).json({
      success: true,
      message: 'Quiz evaluated successfully',
      data: {
        quizId: quiz._id,
        score: correctCount,
        totalQuestions,
        incorrectAnswers: incorrectCount,
        percentage,
        passed,
        userAnswers: evaluatedAnswers,
        questions: quiz.questions,
        feedback: feedbackResult.success && feedbackResult.data ? feedbackResult.data.feedback : null,
        feedbackModel: feedbackResult.success && feedbackResult.data ? feedbackResult.data.model : null
      }
    });
  } catch (error) {
    console.error('[QuizController] submitQuizResult error:', error.message);
    res.status(500).json({
      success: false,
      code: 'SERVER_ERROR',
      message: 'Something went wrong while processing your request. Please try again later.'
    });
  }
};

// @desc    Get all quizzes created by current user
// @route   GET /api/quiz/history
// @access  Private (JWT Required)
const getQuizHistory = async (req, res) => {
  try {
    const quizzes = await Quiz.find({ user: req.user._id })
      .select('-questions') // Exclude heavy question arrays for lightweight list
      .sort({ createdAt: -1 });

    res.status(200).json({
      success: true,
      count: quizzes.length,
      data: quizzes
    });
  } catch (error) {
    console.error('[QuizController] getQuizHistory error:', error.message);
    res.status(500).json({
      success: false,
      code: 'SERVER_ERROR',
      message: 'Something went wrong while processing your request. Please try again later.'
    });
  }
};

// @desc    Get single quiz by ID
// @route   GET /api/quiz/:id
// @access  Private (JWT Required)
const getQuizById = async (req, res) => {
  try {
    const quiz = await Quiz.findOne({ _id: req.params.id, user: req.user._id });

    if (!quiz) {
      return res.status(404).json({
        success: false,
        message: 'Quiz not found'
      });
    }

    res.status(200).json({
      success: true,
      data: quiz
    });
  } catch (error) {
    console.error('[QuizController] getQuizById error:', error.message);
    res.status(500).json({
      success: false,
      code: 'SERVER_ERROR',
      message: 'Something went wrong while processing your request. Please try again later.'
    });
  }
};

module.exports = {
  generateQuiz,
  submitQuizResult,
  getQuizHistory,
  getQuizById
};
