const mongoose = require('mongoose');

const questionSchema = new mongoose.Schema({
  question: {
    type: String,
    required: true
  },
  options: {
    type: [String],
    required: true,
    validate: [
      (arr) => arr.length === 4,
      'Each question must have exactly 4 options'
    ]
  },
  correctAnswer: {
    type: String,
    required: true,
    validate: {
      validator(value) {
        return this.options.includes(value);
      },
      message: 'Correct answer must be one of the options'
    }
  }
});

const quizSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true
    },
    sourceType: {
      type: String,
      enum: ['youtube', 'manual'],
      default: 'youtube'
    },
    videoUrl: {
      type: String,
      default: ''
    },
    videoId: {
      type: String,
      default: ''
    },
    title: {
      type: String,
      default: 'Educational YouTube Quiz'
    },
    summary: {
      type: String,
      required: true
    },
    questions: [questionSchema],
    totalQuestions: {
      type: Number,
      default: 0
    },
    // Attempt details - Pure Backend Calculation (Score is NOT generated by AI)
    isAttempted: {
      type: Boolean,
      default: false
    },
    score: {
      type: Number,
      default: 0
    },
    incorrectAnswers: {
      type: Number,
      default: 0
    },
    percentage: {
      type: Number,
      default: 0
    },
    passed: {
      type: Boolean,
      default: false
    },
    userAnswers: [
      {
        questionIndex: Number,
        selectedAnswer: String,
        isCorrect: Boolean
      }
    ]
  },
  {
    timestamps: true
  }
);

module.exports = mongoose.model('Quiz', quizSchema);
